name: flutter_google_wallet
description: A Flutter Google Wallet Plugin
version: 0.2.0
homepage: https://github.com/voyages-sncf-technologies/flutter_google_wallet

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^22.5.0
  intl_utils: ^2.8.7
  golden_toolkit: ^0.15.0
  melos: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: sncf.connect.tech.flutter_google_wallet
        pluginClass: FlutterGoogleWalletPlugin

  assets:
    - lib/assets/svg/button/

flutter_intl:
  enabled: true
  class_name: I18nGoogleWallet
  main_locale: fr
